(function(g){var window=this;var qIa=function(a,b){return g.Mb(a,b)},w4=function(a,b,c){a.l.set(b,c)},x4=function(a){w4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Sa()).toString(36));
return a},y4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Xm(a.l,b,c)},rIa=function(a,b){var c=[];
g.bj(b,function(d){try{var e=g.Kn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Jn(e)&&c.push(d)},a);
return c},sIa=function(a,b){var c=rIa(a,b);
g.Ab(c,function(d){g.Kn.prototype.remove.call(this,d)},a)},tIa=function(a){if(a.W){if(a.W.locationOverrideToken)return{locationOverrideToken:a.W.locationOverrideToken};
if(null!=a.W.latitudeE7&&null!=a.W.longitudeE7)return{latitudeE7:a.W.latitudeE7,longitudeE7:a.W.longitudeE7}}return null},uIa=function(a,b){g.fb(a,b)||a.push(b)},z4=function(a){var b=0,c;
for(c in a)b++;return b},vIa=function(a,b){var c=b instanceof g.Gc?b:g.Mc(b,/^data:image\//i.test(b));
a.src=g.Hc(c)},wIa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},xIa=function(a){if(a.qg&&"function"==typeof a.qg)return a.qg();
if("string"===typeof a)return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Jb(a)},yIa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||"string"===typeof a)g.Ab(a,b,void 0);else{if(a.nh&&"function"==typeof a.nh)var c=a.nh();else if(a.qg&&"function"==typeof a.qg)c=void 0;else if(g.Ma(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Kb(a);d=xIa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},zIa=function(a,b,c,d){var e=new g.Lm(null,void 0);
a&&g.Mm(e,a);b&&g.Nm(e,b);c&&g.Om(e,c);d&&(e.J=d);return e},A4=function(){},B4=function(a,b){g.zo[a]=!0;
var c=g.xo();c&&c.publish.apply(c,arguments);g.zo[a]=!1},C4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Im;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",AIa(this,a.capabilities||""),BIa(this,a.experiments||""))},AIa=function(a,b){a.capabilities.clear();
g.Ne(b.split(","),g.Qa(qIa,CIa)).forEach(function(c){a.capabilities.add(c)})},BIa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},D4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},E4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},DIa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},EIa=function(a){return new D4(a)},FIa=function(a){return Array.isArray(a)?g.Qc(a,EIa):[]},F4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},G4=function(a){return Array.isArray(a)?"["+g.Qc(a,F4).join(",")+"]":"null"},H4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},GIa=function(a){return g.Qc(a,function(b){return{key:b.id,
name:b.name}})},I4=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},J4=function(a,b){return g.cb(a,function(c){return E4(c,b)})},HIa=function(){var a=(0,g.Eu)();
a&&sIa(a,a.i.Nj(!0))},K4=function(){var a=g.Hu("yt-remote-connected-devices")||[];
g.xb(a);return a},IIa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Qc(a,function(d,e){return 0==e?d:d.substring(c.length)})},JIa=function(a){g.Gu("yt-remote-connected-devices",a,86400)},M4=function(){if(L4)return L4;
var a=g.Hu("yt-remote-device-id");a||(a=H4(),g.Gu("yt-remote-device-id",a,31536E3));for(var b=K4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return L4=d},N4=function(){var a=K4(),b=M4();
g.fb(a,b);g.Ju()&&g.zb(a,b);a=IIa(a);if(g.gb(a))try{g.Qq("remote_sid")}catch(c){}else try{g.Oq("remote_sid",a.join(","),-1)}catch(c){}},KIa=function(){return g.Hu("yt-remote-session-browser-channel")},LIa=function(){return g.Hu("yt-remote-local-screens")||[]},MIa=function(){g.Gu("yt-remote-lounge-token-expiration",!0,86400)},NIa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Qc(LIa(),function(d){return d.loungeToken}),c=g.Qc(a,function(d){return d.loungeToken});
g.fh(c,function(d){return!g.fb(b,d)})&&MIa();
g.Gu("yt-remote-local-screens",a,31536E3)},OIa=function(a,b){g.Gu("yt-remote-session-browser-channel",a);
g.Gu("yt-remote-session-screen-id",b);var c=K4(),d=M4();g.fb(c,d)||c.push(d);JIa(c);N4()},O4=function(a){a||(g.Iu("yt-remote-session-screen-id"),g.Iu("yt-remote-session-video-id"));
N4();a=K4();g.kb(a,M4());JIa(a)},PIa=function(){if(!P4){var a=g.Un();
a&&(P4=new g.En(a))}},QIa=function(){PIa();
return P4?!!P4.get("yt-remote-use-staging-server"):!1},Q4=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},RIa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},SIa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},R4=function(a){a.length?TIa(a.shift(),function(){R4(a)}):S4()},UIa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},TIa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.nd(d,g.kg(a));(document.head||document.documentElement).appendChild(d)},VIa=function(){var a=Q4(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},S4=function(){var a=SIa();
a&&a(!1,"No cast extension found")},T4=function(){if(WIa){var a=2,b=SIa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;TIa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",S4,c)}},XIa=function(){T4();
var a=VIa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");R4(a)},ZIa=function(){T4();
var a=VIa();a.push.apply(a,g.la(YIa.map(UIa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");R4(a)},U4=function(a,b,c){g.E.call(this);
this.I=null!=c?(0,g.B)(a,c):a;this.Hf=b;this.C=(0,g.B)(this.LJ,this);this.i=!1;this.l=0;this.u=this.gb=null;this.B=[]},V4=function(a,b,c){g.E.call(this);
this.B=null!=c?a.bind(c):a;this.Hf=b;this.u=null;this.i=!1;this.l=0;this.gb=null},W4=function(a){a.gb=g.Gm(function(){a.gb=null;
a.i&&!a.l&&(a.i=!1,W4(a))},a.Hf);
var b=a.u;a.u=null;a.B.apply(null,b)},X4=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return wIa(a)},Y4=function(){},Z4=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},a5=function(a){$4.dispatchEvent(new $Ia($4,a))},$Ia=function(a,b){g.Cl.call(this,"statevent",a);
this.stat=b},b5=function(){},aJa=function(){},cJa=function(a){return(a=bJa(a))?new ActiveXObject(a):new XMLHttpRequest},bJa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},c5=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.A_(this);this.u=new g.Fm;this.u.setInterval(250)},eJa=function(a,b,c){a.Dp=1;
a.Rk=x4(b.clone());a.Dn=c;a.I=!0;dJa(a,null)},d5=function(a,b,c,d,e){a.Dp=1;
a.Rk=x4(b.clone());a.Dn=null;a.I=c;e&&(a.MG=!1);dJa(a,d)},dJa=function(a,b){a.pp=Date.now();
e5(a);a.Ql=a.Rk.clone();y4(a.Ql,"t",a.J);a.Es=0;a.Be=a.i.Ax(a.i.Zr()?b:null);0<a.xw&&(a.Ru=new V4((0,g.B)(a.IH,a,a.Be),a.xw));a.B.ya(a.Be,"readystatechange",a.aQ);var c=a.jm?g.Vb(a.jm):{};a.Dn?(a.Ev="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Be.send(a.Ql,a.Ev,a.Dn,c)):(a.Ev="GET",a.MG&&!g.De&&(c.Connection="close"),a.Be.send(a.Ql,a.Ev,null,c));a.i.di(1)},hJa=function(a,b,c){for(var d=!0;!a.Mm&&a.Es<c.length;){var e=fJa(a,c);
if(e==f5){4==b&&(a.Lk=4,a5(15),d=!1);break}else if(e==gJa){a.Lk=4;a5(16);d=!1;break}else g5(a,e)}4==b&&0==c.length&&(a.Lk=1,a5(17),d=!1);a.vi=a.vi&&d;d||(h5(a),i5(a))},fJa=function(a,b){var c=a.Es,d=b.indexOf("\n",c);
if(-1==d)return f5;c=Number(b.substring(c,d));if(isNaN(c))return gJa;d+=1;if(d+c>b.length)return f5;var e=b.substr(d,c);a.Es=d+c;return e},jJa=function(a,b){a.pp=Date.now();
e5(a);var c=b?window.location.hostname:"";a.Ql=a.Rk.clone();w4(a.Ql,"DOMAIN",c);w4(a.Ql,"t",a.J);try{a.zi=new ActiveXObject("htmlfile")}catch(n){h5(a);a.Lk=7;a5(22);i5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in j5)h=j5[h];else if(h in iJa)h=j5[h]=iJa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
j5[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.kd(g.gc("b/12014412"),d+"</body></html>");a.zi.open();a.zi.write(g.gd(c));a.zi.close();a.zi.parentWindow.m=(0,g.B)(a.vP,a);a.zi.parentWindow.d=(0,g.B)(a.YF,a,!0);a.zi.parentWindow.rpcClose=(0,g.B)(a.YF,a,!1);c=a.zi.createElement("DIV");a.zi.parentWindow.document.body.appendChild(c);d=g.Lc(a.Ql.toString());d=g.sd(g.Hc(d));d=g.kd(g.gc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ld(c,d);a.i.di(1)},e5=function(a){a.MA=Date.now()+
a.C;
kJa(a,a.C)},kJa=function(a,b){if(null!=a.Jp)throw Error("WatchDog timer not null");
a.Jp=Z4((0,g.B)(a.DP,a),b)},k5=function(a){a.Jp&&(g.A.clearTimeout(a.Jp),a.Jp=null)},i5=function(a){a.i.LB()||a.Mm||a.i.Us(a)},h5=function(a){k5(a);
g.Ei(a.Ru);a.Ru=null;a.u.stop();g.KCa(a.B);if(a.Be){var b=a.Be;a.Be=null;b.abort();b.dispose()}a.zi&&(a.zi=null)},g5=function(a,b){try{a.i.PF(a,b),a.i.di(4)}catch(c){}},mJa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;lJa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){mJa(a,b,c,d,f)},f)})}},lJa=function(a,b,c){var d=new Image;
d.onload=function(){try{l5(d),c(!0)}catch(e){}};
d.onerror=function(){try{l5(d),c(!1)}catch(e){}};
d.onabort=function(){try{l5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{l5(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
vIa(d,a)},l5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},m5=function(a){g.Wl.call(this);
this.headers=new g.Im;this.ea=a||null;this.B=!1;this.ca=this.i=null;this.za=this.W="";this.I=0;this.u="";this.C=this.la=this.L=this.ga=!1;this.J=0;this.X=null;this.Ca="";this.Y=this.ia=!1},nJa=function(a){return g.Be&&g.be(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},oJa=function(a){return"content-type"==a.toLowerCase()},qJa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.I=5;pJa(a);n5(a)},pJa=function(a){a.ga||(a.ga=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},sJa=function(a){if(a.B&&"undefined"!=typeof g.D_)if(a.ca[1]&&4==o5(a)&&2==a.getStatus())p5(a,"Local request error detected and ignored");
else if(a.L&&4==o5(a))g.Gm(a.MF,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){p5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Bd(1,String(a.W));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!rJa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<o5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";pJa(a)}}finally{n5(a)}}},n5=function(a,b){if(a.i){tJa(a);
var c=a.i,d=a.ca[0]?g.Ia:null;a.i=null;a.ca=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},tJa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},o5=function(a){return a.i?a.i.readyState:0},q5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},p5=function(a,b){return b+" ["+a.za+" "+a.W+" "+a.getStatus()+"]"},uJa=function(a){this.i=a;
this.l=new Y4},vJa=function(a){var b=r5(a.i,a.kq,"/mail/images/cleardot.gif");
x4(b);mJa(b.toString(),5E3,(0,g.B)(a.CK,a),3,2E3);a.di(1)},t5=function(a){var b=a.i.L;
if(null!=b)a5(5),b?(a5(11),s5(a.i,a,!1)):(a5(12),s5(a.i,a,!0));else if(a.zg=new c5(a,void 0,void 0,void 0),a.zg.jm=a.yw,b=a.i,b=r5(b,b.Zr()?a.aq:null,a.zw),a5(5),!g.Be||g.de(10))y4(b,"TYPE","xmlhttp"),d5(a.zg,b,!1,a.aq,!1);else{y4(b,"TYPE","html");var c=a.zg;a=!!a.aq;c.Dp=3;c.Rk=x4(b.clone());jJa(c,a)}},u5=function(a,b,c){this.Ma=1;
this.i=[];this.u=[];this.B=new Y4;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},wJa=function(a,b){this.i=a;
this.map=b;this.context=null},xJa=function(a,b,c,d){g.Cl.call(this,"timingevent",a);
this.size=b;this.Sr=d},yJa=function(a){g.Cl.call(this,"serverreachability",a)},BJa=function(a){zJa(a);
if(3==a.Ma){var b=a.yr++,c=a.At.clone();w4(c,"SID",a.l);w4(c,"RID",b);w4(c,"TYPE","terminate");v5(a,c);b=new c5(a,a.l,b,void 0);b.Dp=2;b.Rk=x4(c.clone());vIa(new Image,b.Rk.toString());b.pp=Date.now();e5(b)}AJa(a)},CJa=function(a){a.WK(1,0);
a.At=r5(a,null,a.Aw);w5(a)},zJa=function(a){a.Vk&&(a.Vk.abort(),a.Vk=null);
a.Wd&&(a.Wd.cancel(),a.Wd=null);a.Pj&&(g.A.clearTimeout(a.Pj),a.Pj=null);x5(a);a.ng&&(a.ng.cancel(),a.ng=null);a.il&&(g.A.clearTimeout(a.il),a.il=null)},DJa=function(a,b){if(0==a.Ma)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new wJa(a.uM++,b));2!=a.Ma&&3!=a.Ma||w5(a)},EJa=function(a){var b=0;
a.Wd&&b++;a.ng&&b++;return b},w5=function(a){a.ng||a.il||(a.il=Z4((0,g.B)(a.WF,a),0),a.zo=0)},GJa=function(a,b){if(1==a.Ma){if(!b){a.yr=Math.floor(1E5*Math.random());
var c=a.yr++,d=new c5(a,"",c,void 0);d.jm=a.Fi;var e=y5(a),f=a.At.clone();w4(f,"RID",c);w4(f,"CVER","1");v5(a,f);eJa(d,f,e);a.ng=d;a.Ma=2}}else 3==a.Ma&&(b?FJa(a,b):0==a.i.length||a.ng||FJa(a))},FJa=function(a,b){if(b)if(6<a.Nm){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.yr-1;var d=y5(a)}else c=b.L,d=b.Dn;else c=a.yr++,d=y5(a);var e=a.At.clone();w4(e,"SID",a.l);w4(e,"RID",c);w4(e,"AID",a.So);v5(a,e);c=new c5(a,a.l,c,a.zo+1);c.jm=a.Fi;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ng=c;eJa(c,e,d)},v5=function(a,b){if(a.zf){var c=a.zf.wD();
c&&g.Cb(c,function(d,e){w4(b,e,d)})}},y5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Nm&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Tn:e.Tn},f++){e.Tn=a.i[f].i;var h=a.i[f].map;e.Tn=6>=a.Nm?f:e.Tn-d;try{g.Cb(h,function(l){return function(m,n){c.push("req"+l.Tn+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Tn+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},HJa=function(a){a.Wd||a.Pj||(a.I=1,a.Pj=Z4((0,g.B)(a.VF,a),0),a.ho=0)},z5=function(a){if(a.Wd||a.Pj||3<=a.ho)return!1;
a.I++;a.Pj=Z4((0,g.B)(a.VF,a),IJa(a,a.ho));a.ho++;return!0},s5=function(a,b,c){a.Cv=c;
a.Gi=b.Lj;a.C||CJa(a)},x5=function(a){null!=a.Um&&(g.A.clearTimeout(a.Um),a.Um=null)},IJa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},A5=function(a,b){if(2==b||9==b){var c=null;
a.zf&&(c=null);var d=(0,g.B)(a.IQ,a);c||(c=new g.Lm("//www.google.com/images/cleardot.gif"),x4(c));lJa(c.toString(),1E4,d)}else a5(2);JJa(a,b)},JJa=function(a,b){a.Ma=0;
a.zf&&a.zf.MC(b);AJa(a);zJa(a)},AJa=function(a){a.Ma=0;
a.Gi=-1;if(a.zf)if(0==a.u.length&&0==a.i.length)a.zf.jx();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.zf.jx(b)}},r5=function(a,b,c){var d=g.Tm(c);
if(""!=d.i)b&&g.Nm(d,b+"."+d.i),g.Om(d,d.u);else{var e=window.location;d=zIa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Eq&&g.Cb(a.Eq,function(f,h){w4(d,h,f)});
w4(d,"VER",a.Nm);v5(a,d);return d},KJa=function(){},LJa=function(){this.i=[];
this.l=[]},MJa=function(a,b){this.action=a;
this.params=b||{}},B5=function(a,b){g.E.call(this);
this.i=new g.M(this.nP,0,this);g.I(this,this.i);this.Hf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.B)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},C5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ca=a;this.I=b;this.u=new g.Dn;this.l=new B5(this.kQ,this);this.i=null;this.X=!1;this.C=null;this.W="";this.L=this.B=0;this.J=[];this.ea=c;this.Y=d;this.ia=e},NJa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Cv,sessionId:a.i.l,arrayId:a.i.So}},OJa=function(a,b){a.L=b||0;
a.l.stop();D5(a);a.i&&(3==a.i.getState()&&GJa(a.i),BJa(a.i));a.L=0},E5=function(a){return!!a.i&&3==a.i.getState()},D5=function(a){if(a.i){var b=a.Y(),c=a.i.Fi||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Fi=c}},F5=function(a){this.scheme="https";
this.port=this.domain="";this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.Bd(4,a))||"";b&&(this.port=":"+b);this.domain=g.Cd(a)||"";a=g.Wc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ec(a,"10.0")&&(this.l=!1))},G5=function(a,b){var c=a.i;
a.l&&(c=a.scheme+"://"+a.domain+a.port+a.i);return g.Od(c+b,{})},H5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.B,d,!0),onError:g.Qa(a.u,e),onTimeout:g.Qa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Tp(b,a)},SJa=function(){var a=PJa;
QJa();I5.push(a);RJa()},J5=function(a,b){QJa();
var c=TJa(a,String(b));g.gb(I5)?UJa(c):(RJa(),g.Ab(I5,function(d){d(c)}))},QJa=function(){I5||(I5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Da("yt.mdx.remote.debug.handlers_",I5,void 0))},UJa=function(a){var b=(K5+1)%50;
K5=b;L5[b]=a;M5||(M5=49==b)},RJa=function(){var a=I5;
if(L5[0]){var b=M5?K5:-1;do{b=(b+1)%50;var c=L5[b];g.Ab(a,function(d){d(c)})}while(b!=K5);
L5=Array(50);K5=-1;M5=!1}},TJa=function(a,b){var c=(Date.now()-VJa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},N5=function(a){g.R.call(this);
this.I=a;this.screens=[]},WJa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},XJa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ne(a.screens,function(f){return!!I4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=WJa(a,b[d])||c;return c},YJa=function(a,b){var c=a.screens.length;
a.screens=g.Ne(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},O5=function(a,b,c,d,e){g.R.call(this);
this.u=a;this.J=b;this.B=c;this.I=d;this.C=e;this.l=0;this.i=null;this.gb=NaN},Q5=function(a){N5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;P5(this);this.info("Initializing with "+G4(this.screens))},ZJa=function(a){if(a.screens.length){var b=g.Qc(a.screens,function(d){return d.id}),c=G5(a.l,"/pairing/get_lounge_token_batch");
H5(a.l,c,{screen_ids:b.join(",")},(0,g.B)(a.xL,a),(0,g.B)(a.wL,a))}},P5=function(a){if(g.Ko("deprecate_pair_servlet_enabled"))return XJa(a,[]);
var b=FIa(LIa());b=g.Ne(b,function(c){return!c.uuid});
return XJa(a,b)},R5=function(a,b){NIa(g.Qc(a.screens,DIa));
b&&MIa()},T5=function(a,b){g.R.call(this);
this.I=b;var c=g.Hu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.i=d;this.C=a;this.u=this.B=NaN;this.l=null;S5("Initialized with "+g.Dj(this.i))},U5=function(a,b,c){var d=G5(a.C,"/pairing/get_screen_availability");
H5(a.C,d,{lounge_token:b.token},(0,g.B)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},V5=function(a,b){a:if(z4(b)!=z4(a.i))var c=!1;
else{c=g.Kb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(S5("Updated online screens: "+g.Dj(a.i)),a.i=b,a.V("screenChange"));$Ja(a)},W5=function(a){isNaN(a.u)||g.wo(a.u);
a.u=g.uo((0,g.B)(a.Mz,a),0<a.B&&a.B<g.Sa()?2E4:1E4)},S5=function(a){J5("OnlineScreenService",a)},aKa=function(a){var b={};
g.Ab(a.I(),function(c){c.token?b[c.token]=c.id:this.Gd("Requesting availability of screen w/o lounge token.")});
return b},$Ja=function(a){a=g.Kb(g.Db(a.i,function(b){return b}));
g.xb(a);a.length?g.Gu("yt-remote-online-screen-ids",a.join(","),60):g.Iu("yt-remote-online-screen-ids")},X5=function(a){N5.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.u=[];this.C={};bKa(this)},dKa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Kg();if(h=(c?J4(h,c):null)||J4(h,b)){h.uuid=b;var l=Y5(a,h);U5(a.i,l,function(m){e(m?l:null)})}else c?cKa(a,c,(0,g.B)(function(m){var n=Y5(this,new D4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));U5(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},eKa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},fKa=function(a,b,c){U5(a.i,b,c)},cKa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Tp(G5(a.B,"/pairing/get_lounge_token_batch"),e)},gKa=function(a){a.screens=a.l.Kg();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+G4(a.screens))},bKa=function(a){Z5(a);
a.l=new Q5(a.B);a.l.subscribe("screenChange",(0,g.B)(a.DL,a));gKa(a);a.u=FIa(g.Hu("yt-remote-automatic-screen-cache")||[]);Z5(a);a.info("Initializing automatic screens: "+G4(a.u));a.i=new T5(a.B,(0,g.B)(a.Kg,a,!0));a.i.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},Y5=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=J4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),hKa(a));Z5(a);a.C[b.uuid]=b.id;g.Gu("yt-remote-device-id-map",a.C,31536E3);return b},hKa=function(a){a=g.Ne(a.u,function(b){return"shortLived"!=b.idType});
g.Gu("yt-remote-automatic-screen-cache",g.Qc(a,DIa))},Z5=function(a){a.C=g.Hu("yt-remote-device-id-map")||{}},$5=function(a,b,c){g.R.call(this);
this.ia=c;this.u=a;this.i=b;this.B=null},a6=function(a,b){a.B=b;
a.V("sessionScreen",a.B)},iKa=function(a,b){a.B&&(a.B.token=b,Y5(a.u,a.B));
a.V("sessionScreen",a.B)},b6=function(a,b){J5(a.ia,b)},c6=function(a,b,c){$5.call(this,a,b,"CastSession");
var d=this;this.ga=c;this.l=null;this.Y=(0,g.B)(this.QJ,this);this.ea=(0,g.B)(this.HP,this);this.X=g.uo(function(){jKa(d,null)},12E4);
this.J=this.C=this.I=this.L=0;this.ca=!1;this.W="unknown"},d6=function(a,b){g.wo(a.J);
a.J=0;0==b?kKa(a):a.J=g.uo(function(){kKa(a)},b)},kKa=function(a){lKa(a,"getLoungeToken");
g.wo(a.C);a.C=g.uo(function(){mKa(a,null)},3E4)},lKa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Dj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.B)(function(){b6(this,"Failed to send message: "+b+".")},a)):b6(a,"Sending yt message without session: "+g.Dj(c))},e6=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.ND(b,function(c){a6(a,c)},function(){return a.ag()},5)):a.ag(Error("Waiting for session status timed out."))},oKa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new D4(b);nKa(a,d,function(e){e?(a.ca=!0,Y5(a.u,d),a6(a,d),a.W="unknown",d6(a,c)):(g.ro(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.ag())},5)},jKa=function(a,b){g.wo(a.X);
a.X=0;b?a.ga.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?oKa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.ro(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),e6(a,b.screenId))):(g.ro(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
e6(a,b.screenId)):e6(a,b.screenId):a.ag(Error("Waiting for session status timed out."))},mKa=function(a,b){g.wo(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.W=c,d6(a,3E4)):(iKa(a,b.loungeToken),a.ca=!1,a.W="unknown",d6(a,b.loungeTokenRefreshIntervalMs))},nKa=function(a,b,c,d){g.wo(a.I);
a.I=0;fKa(a.u,b,function(e){e||0>d?c(e):a.I=g.uo(function(){nKa(a,b,c,d-1)},300)})},pKa=function(a){g.wo(a.L);
a.L=0;g.wo(a.I);a.I=0;g.wo(a.X);a.X=0;g.wo(a.C);a.C=0;g.wo(a.J);a.J=0},f6=function(a,b,c,d){$5.call(this,a,b,"DialSession");
this.ma=d;this.l=this.L=null;this.ea="";this.za=c;this.la=null;this.X=g.Ia;this.W=NaN;this.ga=(0,g.B)(this.RJ,this);this.C=g.Ia;this.J=this.I=0;this.Y=!1;this.ca="unknown"},g6=function(a){var b;
return!!(a.ma.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},qKa=function(a){a.C=a.u.NB(a.ea,a.i.label,a.i.friendlyName,g6(a),function(b,c){a.C=g.Ia;
a.Y=!0;a6(a,b);"shortLived"==b.idType&&0<c&&h6(a,c)},function(b){a.C=g.Ia;
a.ag(b)})},rKa=function(a){var b={};
b.pairingCode=a.ea;b.theme=a.za;QIa()&&(b.env_useStageMdx=1);return g.Md(b)},i6=function(a){return new Promise(function(b){a.ea=H4();
if(a.la){var c=new chrome.cast.DialLaunchResponse(!0,rKa(a));b(c);qKa(a)}else a.X=function(){g.wo(a.W);a.X=function(){};
a.W=NaN;var d=new chrome.cast.DialLaunchResponse(!0,rKa(a));b(d);qKa(a)},a.W=g.uo(function(){a.X()},100)})},tKa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new D4(b);return(new Promise(function(e){sKa(a,d,function(f){f?(a.Y=!0,Y5(a.u,d),a6(a,d),h6(a,c)):g.ro(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):i6(a)})},uKa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){dKa(a.u,c,b,d,function(f){f&&f.token&&a6(a,f);e(f)},function(f){b6(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):i6(a)})},sKa=function(a,b,c,d){g.wo(a.I);
a.I=0;fKa(a.u,b,function(e){e||0>d?c(e):a.I=g.uo(function(){sKa(a,b,c,d-1)},300)})},h6=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
g6(a)&&(g.wo(a.J),a.J=0,0==b?vKa(a):a.J=g.uo(function(){vKa(a)},b))},vKa=function(a){g6(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ca=c,h6(a,3E4)):(a.Y=!1,a.ca="unknown",iKa(a,b.loungeToken),h6(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ca="noLoungeTokenResponse";h6(a,3E4)})},wKa=function(a){g.wo(a.I);
a.I=0;g.wo(a.J);a.J=0;a.C();a.C=function(){};
g.wo(a.W)},j6=function(a,b){$5.call(this,a,b,"ManualSession");
this.l=g.uo((0,g.B)(this.To,this,null),150)},k6=function(a,b){g.R.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.W=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.I=(0,g.B)(this.DO,this)},xKa=function(a,b){return b?g.cb(a.u,function(c){return E4(b,c.label)},a):null},l6=function(a){J5("Controller",a)},PJa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},m6=function(a){return a.J||!!a.u.length||!!a.i},n6=function(a,b,c){b!=a.i&&(g.Ei(a.i),(a.i=b)?(c?a.V("yt-remote-cast2-receiver-resumed",
b.i):a.V("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.B)(a.TF,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.To(null)):a.V("yt-remote-cast2-session-change",null))},yKa=function(a){var b=a.l.MB(),c=a.i&&a.i.i;
a=g.Qc(b,function(d){c&&E4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=xKa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},DKa=function(a,b,c,d){d.disableCastApi?o6("Cannot initialize because disabled by Mdx config."):zKa()?AKa(b,d)&&(p6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?BKa(a,c):(window.__onGCastApiAvailable=function(e,f){e?BKa(a,c):(q6("Failed to load cast API: "+f),r6(!1),p6(!1),g.Iu("yt-remote-cast-available"),g.Iu("yt-remote-cast-receiver"),
CKa(),c(!1))},d.loadCastApiSetupScript?g.Go("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=Q4()&&XIa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?S4():89<=Q4()?ZIa():(T4(),R4(YIa.map(UIa))))):o6("Cannot initialize because not running Chrome")},CKa=function(){o6("dispose");
var a=s6();a&&a.dispose();g.Da("yt.mdx.remote.cloudview.instance_",null,void 0);EKa(!1);g.Co(t6);t6.length=0},u6=function(){return!!g.Hu("yt-remote-cast-installed")},FKa=function(){var a=g.Hu("yt-remote-cast-receiver");
return a?a.friendlyName:null},GKa=function(){o6("clearCurrentReceiver");
g.Iu("yt-remote-cast-receiver")},HKa=function(){return u6()?s6()?s6().getCastSession():(q6("getCastSelector: Cast is not initialized."),null):(q6("getCastSelector: Cast API is not installed!"),null)},w6=function(){u6()?s6()?v6()?(o6("Requesting cast selector."),s6().requestSession()):(o6("Wait for cast API to be ready to request the session."),t6.push(g.Bo("yt-remote-cast2-api-ready",w6))):q6("requestCastSelector: Cast is not initialized."):q6("requestCastSelector: Cast API is not installed!")},x6=
function(a,b){v6()?s6().setConnectedScreenStatus(a,b):q6("setConnectedScreenStatus called before ready.")},zKa=function(){var a=0<=g.Wc.search(/ (CrMo|Chrome|CriOS)\//);
return g.GA||a},IKa=function(a,b){s6().init(a,b)},AKa=function(a,b){var c=!1;
s6()||(c=new k6(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.Gu("yt-remote-cast-available",d);B4("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){o6("onReceiverSelected: "+d.friendlyName);
g.Gu("yt-remote-cast-receiver",d);B4("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){o6("onReceiverResumed: "+d.friendlyName);
g.Gu("yt-remote-cast-receiver",d);B4("yt-remote-cast2-receiver-resumed",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){o6("onSessionChange: "+F4(d));
d||g.Iu("yt-remote-cast-receiver");B4("yt-remote-cast2-session-change",d)}),g.Da("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
o6("cloudview.createSingleton_: "+c);return c},s6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},BKa=function(a,b){r6(!0);
p6(!1);IKa(a,function(c){c?(EKa(!0),g.Do("yt-remote-cast2-api-ready")):(q6("Failed to initialize cast API."),r6(!1),g.Iu("yt-remote-cast-available"),g.Iu("yt-remote-cast-receiver"),CKa());b(c)})},o6=function(a){J5("cloudview",a)},q6=function(a){J5("cloudview",a)},r6=function(a){o6("setCastInstalled_ "+a);
g.Gu("yt-remote-cast-installed",a)},v6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},EKa=function(a){o6("setApiReady_ "+a);
g.Da("yt.mdx.remote.cloudview.apiReady_",a,void 0)},p6=function(a){g.Da("yt.mdx.remote.cloudview.initializing_",a,void 0)},y6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.J=this.L=0;this.i=null;this.hasNext=this.Xi=!1;this.W=this.I=this.l=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},z6=function(a){a.audioTrackId=null;
a.i=null;a.playerState=-1;a.Xi=!1;a.hasNext=!1;a.L=0;a.J=g.Sa();a.C=0;a.l=0;a.I=0;a.W=0;a.B=NaN;a.u=!1},A6=function(a){return a.Lb()?(g.Sa()-a.J)/1E3:0},B6=function(a,b){a.L=b;
a.J=g.Sa()},C6=function(a){switch(a.playerState){case 1:case 1081:return(g.Sa()-a.J)/1E3+a.L;
case -1E3:return 0}return a.L},D6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&z6(a)},E6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Wb(a.i);b.hasPrevious=a.Xi;b.hasNext=a.hasNext;b.playerTime=a.L;b.playerTimeAt=a.J;b.seekableStart=a.C;b.seekableEnd=a.l;b.duration=a.I;b.loadedTime=a.W;b.liveIngestionTime=a.B;return b},G6=function(a,b){g.R.call(this);
this.Ma=0;this.u=a;this.C=[];this.B=new LJa;this.l=this.i=null;this.L=(0,g.B)(this.fN,this);this.I=(0,g.B)(this.Br,this);this.J=(0,g.B)(this.eN,this);this.W=(0,g.B)(this.mN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.aA,this),JKa(this))):c=3;0!=c&&(b?this.aA(c):g.uo((0,g.B)(function(){this.aA(c)},this),0));
var d=HKa();d&&F6(this,d);this.subscribe("yt-remote-cast2-session-change",this.W)},H6=function(a){return new y6(a.u.getPlayerContextData())},JKa=function(a){g.Ab("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Qa(this.AO,b),this))},a)},KKa=function(a){g.Ab(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},I6=function(a){return 1==a.getState()},J6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},L6=function(a,b,c){var d=H6(a);
B6(d,c);-1E3!=d.playerState&&(d.playerState=b);K6(a,d)},M6=function(a,b,c){a.u.sendMessage(b,c)},K6=function(a,b){KKa(a);
a.u.setPlayerContextData(E6(b));JKa(a)},F6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.I),a.Br(null));
a.l=b;a.l&&(J5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.I),a.l.media.length&&a.Br(a.l.media[0]))},LKa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=H6(a);b.contentId!=d.videoId&&J5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;B6(d,a.i.getEstimatedTime());K6(a,d)}else J5("CP","No cast media video. Ignoring state update.")},N6=function(a,b,c){return(0,g.B)(function(d){this.Gd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gd("Retrying "+b+" using MDx browser channel."),M6(this,b,c))},a)},O6=function(a,b,c){g.R.call(this);
this.C=NaN;this.ca=!1;this.L=this.J=this.X=this.Y=NaN;this.W=[];this.B=this.I=this.u=this.Fb=this.i=null;this.ia=a;this.W.push(g.Wo(window,"beforeunload",(0,g.B)(this.rL,this)));this.l=[];this.Fb=new y6;this.ga=b.id;this.ea=b.idType;this.i=MKa(this,c);this.i.subscribe("handlerOpened",this.jN,this);this.i.subscribe("handlerClosed",this.gN,this);this.i.subscribe("handlerError",this.hN,this);this.i.subscribe("handlerMessage",this.iN,this);this.i.bv(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.Fb.videoId;g.Ju()&&g.Gu("yt-remote-session-video-id",d)},this)},P6=function(a){J5("conn",a)},MKa=function(a,b){return new C5(G5(a.ia,"/bc"),b,!1,function(){return a.RB()},"shortLived"==a.ea)},Q6=function(a,b){a.V("proxyStateChange",b)},NKa=function(a){a.C=g.uo((0,g.B)(function(){P6("Connecting timeout");
this.vo(1)},a),2E4)},R6=function(a){g.wo(a.C);
a.C=NaN},S6=function(a){g.wo(a.Y);
a.Y=NaN},OKa=function(a){T6(a);
a.X=g.uo((0,g.B)(function(){U6(this,"getNowPlaying")},a),2E4)},T6=function(a){g.wo(a.X);
a.X=NaN},QKa=function(a,b){b&&(R6(a),S6(a));
var c=E5(a.i)&&isNaN(a.C);b==c?b&&(Q6(a,1),U6(a,"getSubtitlesTrack")):b?(a.MD()&&a.Fb.reset(),Q6(a,1),U6(a,"getNowPlaying"),PKa(a)):a.vo(1)},RKa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Fb.videoId&&(g.Pb(b.params)?a.Fb.i=null:a.Fb.i=b.params,a.V("remotePlayerChange"))},SKa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Fb.listId=b.params.listId||a.Fb.listId;D6(a.Fb,c,d);a.V("remoteQueueChange")},UKa=function(a,b){b.params=b.params||{};
SKa(a,b);TKa(a,b);a.V("autoplayDismissed")},TKa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
B6(a.Fb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Fb.playerState&&(c=-1E3);a.Fb.playerState=c;c=Number(b.params.loadedTime);a.Fb.W=isNaN(c)?0:c;c=Number(b.params.duration);a.Fb.I=isNaN(c)?0:c;c=a.Fb;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.Fb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.l=isNaN(e)?0:e;1==a.Fb.playerState?OKa(a):T6(a);a.V("remotePlayerChange")},VKa=function(a,b){if(-1E3!=
a.Fb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Fb.playerState=c;c=parseInt(b.params.currentTime,10);B6(a.Fb,isNaN(c)?0:c);a.V("remotePlayerChange")}},WKa=function(a,b){var c="true"==b.params.muted;
a.Fb.volume=parseInt(b.params.volume,10);a.Fb.muted=c;a.V("remotePlayerChange")},XKa=function(a,b){a.I=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},YKa=function(a,b){var c="true"==b.params.hasNext;
a.Fb.Xi="true"==b.params.hasPrevious;a.Fb.hasNext=c;a.V("previousNextChange")},PKa=function(a){g.wo(a.L);
a.L=g.uo((0,g.B)(a.vo,a,1),864E5)},U6=function(a,b,c){c?P6("Sending: action="+b+", params="+g.Dj(c)):P6("Sending: action="+b);
a.i.sendMessage(b,c)},V6=function(a){N5.call(this,"ScreenServiceProxy");
this.Gf=a;this.i=[];this.i.push(this.Gf.$_s("screenChange",(0,g.B)(this.VJ,this)));this.i.push(this.Gf.$_s("onlineScreenChange",(0,g.B)(this.hO,this)))},bLa=function(a,b){PIa();
if(!P4||!P4.get("yt-remote-disable-remote-module-for-dev")){b=g.P("MDX_CONFIG")||b;HIa();N4();W6||(W6=new F5(b?b.loungeApiHost:void 0),QIa()&&(W6.i="/api/loungedev"));X6||(X6=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Da("yt.mdx.remote.deferredProxies_",X6,void 0));ZKa();var c=Y6();if(!c){var d=new X5(W6);g.Da("yt.mdx.remote.screenService_",d,void 0);c=Y6();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});DKa(a,d,function(h){h?Z6()&&x6(Z6(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){B4("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ha("yt.mdx.remote.initialized_")){g.Da("yt.mdx.remote.initialized_",!0,void 0);
$6("Initializing: "+g.Dj(b));a7.push(g.Bo("yt-remote-cast2-availability-change",function(){B4("yt-remote-receiver-availability-change")}));
a7.push(g.Bo("yt-remote-cast2-receiver-selected",function(){b7(null);B4("yt-remote-auto-connect","cast-selector-receiver")}));
a7.push(g.Bo("yt-remote-cast2-receiver-resumed",function(){B4("yt-remote-receiver-resumed","cast-selector-receiver")}));
a7.push(g.Bo("yt-remote-cast2-session-change",$Ka));a7.push(g.Bo("yt-remote-connection-change",function(h){h?x6(Z6(),"YouTube TV"):c7()||(x6(null,null),GKa())}));
e=d7();b.isAuto&&(e.id+="#dial");g.Ko("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);$6(" -- with channel params: "+g.Dj(e));e?(g.Gu("yt-remote-session-app",e.app),g.Gu("yt-remote-session-name",e.name)):(g.Iu("yt-remote-session-app"),g.Iu("yt-remote-session-name"));g.Da("yt.mdx.remote.channelParams_",e,void 0);c.start();Z6()||aLa()}}},cLa=function(){var a=Y6().Gf.$_gos();
var b=e7();b&&f7()&&(I4(a,b)||a.push(b));return GIa(a)},g7=function(){var a=dLa();
!a&&u6()&&FKa()&&(a={key:"cast-selector-receiver",name:FKa()});return a},dLa=function(){var a=cLa(),b=e7();
b||(b=c7());return g.cb(a,function(c){return b&&E4(b,c.key)?!0:!1})},e7=function(){var a=Z6();
if(!a)return null;var b=Y6().Kg();return J4(b,a)},$Ka=function(a){$6("remote.onCastSessionChange_: "+F4(a));
if(a){var b=e7();if(b&&b.id==a.id){if(x6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))h7&&(h7.token=a),(b=f7())&&b.bv(a)}else b&&i7(),j7(a,1)}else f7()&&i7()},i7=function(){v6()?s6().stopSession():q6("stopSession called before API ready.");
var a=f7();a&&(a.disconnect(1),k7(null))},l7=function(){var a=f7();
return!!a&&3!=a.getProxyState()},$6=function(a){J5("remote",a)},Y6=function(){if(!m7){var a=g.Ha("yt.mdx.remote.screenService_");
m7=a?new V6(a):null}return m7},Z6=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},eLa=function(a){g.Da("yt.mdx.remote.currentScreenId_",a,void 0)},fLa=function(){return g.Ha("yt.mdx.remote.connectData_")},b7=function(a){g.Da("yt.mdx.remote.connectData_",a,void 0)},f7=function(){return g.Ha("yt.mdx.remote.connection_")},k7=function(a){var b=f7();
b7(null);a||eLa("");g.Da("yt.mdx.remote.connection_",a,void 0);X6&&(g.Ab(X6,function(c){c(a)}),X6.length=0);
b&&!a?B4("yt-remote-connection-change",!1):!b&&a&&B4("yt-remote-connection-change",!0)},c7=function(){var a=g.Ju();
if(!a)return null;var b=Y6();if(!b)return null;b=b.Kg();return J4(b,a)},j7=function(a,b){Z6();
e7()&&e7();if(n7)h7=a;else{eLa(a.id);var c=new O6(W6,a,d7());c.connect(b,fLa());c.subscribe("beforeDisconnect",function(d){B4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){f7()&&(f7(),k7(null))});
c.subscribe("browserChannelAuthError",function(){var d=e7();d&&"shortLived"==d.idType&&(v6()?s6().handleBrowserChannelAuthError():q6("refreshLoungeToken called before API ready."))});
k7(c)}},aLa=function(){var a=c7();
a?($6("Resume connection to: "+F4(a)),j7(a,0)):(O4(),GKa(),$6("Skipping connecting because no session screen found."))},ZKa=function(){var a=d7();
if(g.Pb(a)){a=M4();var b=g.Hu("yt-remote-session-name")||"",c=g.Hu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Da("yt.mdx.remote.channelParams_",a,void 0)}},d7=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},o7=function(a,b,c){g.E.call(this);
var d=this;this.l=a;this.G=b;this.wb=c;this.events=new g.ZM(this);this.X=this.events.N(this.G,"onVolumeChange",function(e){gLa(d,e)});
this.C=!1;this.suggestion=null;this.I=new g.dK(64);this.i=new g.M(this.WG,500,this);this.u=new g.M(this.XG,1E3,this);this.L=new U4(this.ZQ,0,this);this.B={};this.W=new g.M(this.yH,1E3,this);this.J=new V4(this.seekTo,1E3,this);this.Y=g.Ia;g.I(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.QN);this.events.N(b,"captionschanged",this.cN);this.events.N(b,"captionssettingschanged",this.cH);this.events.N(b,"videoplayerreset",this.Lu);this.events.N(b,"mdxautoplaycancel",function(){d.wb.gD()});
a=this.wb;a.na();a.subscribe("proxyStateChange",this.OF,this);a.subscribe("remotePlayerChange",this.Hr,this);a.subscribe("remoteQueueChange",this.Lu,this);a.subscribe("previousNextChange",this.LF,this);a.subscribe("nowAutoplaying",this.GF,this);a.subscribe("autoplayDismissed",this.gF,this);g.I(this,this.i);g.I(this,this.u);g.I(this,this.L);g.I(this,this.W);g.I(this,this.J);this.cH();this.Lu();this.Hr()},gLa=function(a,b){if(p7(a)){a.wb.unsubscribe("remotePlayerChange",a.Hr,a);
var c=Math.round(b.volume),d=!!b.muted,e=H6(a.wb);if(c!==e.volume||d!==e.muted)a.wb.setVolume(c,d),a.W.start();a.wb.subscribe("remotePlayerChange",a.Hr,a)}},hLa=function(a){a.Ab(0);
a.i.stop();a.tb(new g.dK(64))},q7=function(a,b){if(p7(a)&&!a.C){var c=null;
b&&(c={style:a.G.getSubtitlesUserSettings()},g.Yb(c,b));a.wb.QB(a.G.getVideoData(1).videoId,c);a.B=H6(a.wb).i}},r7=function(a,b){var c=a.G.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.G.getVideoData(1);a.wb.playVideo(c.videoId,b,d,e,c.playerParams,c.ia,tIa(c));a.tb(new g.dK(1))},iLa=function(a,b){if(b){var c=a.G.getOption("captions","tracklist",{fE:1});
c&&c.length?(a.G.setOption("captions","track",b),a.C=!1):(a.G.loadModule("captions"),a.C=!0)}else a.G.setOption("captions","track",{})},p7=function(a){return H6(a.wb).videoId===a.G.getVideoData(1).videoId},s7=function(){g.W.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",ba:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",ka:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],ba:"Learn more"},{D:"button",ka:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],ba:"OK"}]}]}]});this.i=new g.NL(this,250);this.learnMoreButton=
this.ha("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ha("ytp-mdx-manual-pairing-popup-ok");g.I(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},t7=function(){g.W.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",ba:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",ba:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",ka:["ytp-button","ytp-mdx-privacy-popup-cancel"],ba:"Cancel"},{D:"button",ka:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],ba:"Confirm"}]}]}]});this.i=new g.NL(this,250);this.cancelButton=this.ha("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ha("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},u7=function(a){g.W.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.yma()]},{D:"div",K:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.api=a;this.i=new g.NL(this,250);g.I(this,this.i);this.N(a,"presentingplayerstatechange",this.l);jLa(this,a.Xa())},jLa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.V(b,128)?g.CJ("Error on $RECEIVER_NAME",c):b.Lb()||g.V(b,4)?g.CJ("Playing on $RECEIVER_NAME",c):g.CJ("Connected to $RECEIVER_NAME",c);a.Aa("statustext",c);a.i.show()}else a.i.hide()},v7=function(a,b){g.RP.call(this,"Play on",0,a,b);
this.G=a;this.Nl={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},w7=function(a){g.gN.call(this,a);
this.ai={key:H4(),name:"This computer"};this.hh=null;this.subscriptions=[];this.Bz=this.wb=null;this.Nl=[this.ai];this.Xk=this.ai;this.Mc=new g.dK(64);this.AE=0;this.Me=-1;this.Xo=null;this.Kr=this.pu=!1;this.Cn=this.mp=null;if(!g.aG(this.player.T())){a=this.player;var b=g.NM(a);b&&(b=b.en())&&(b=new v7(a,b),g.I(this,b));b=new u7(a);g.I(this,b);g.XM(a,b.element,4);this.mp=new t7;g.I(this,this.mp);g.XM(a,this.mp.element,4);g.T(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.T(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.Xo=new s7,g.I(this,this.Xo),g.XM(a,this.Xo.element,4));this.Kr=!!c7();this.pu=!!g.Hu("yt-remote-manual-pairing-warning-shown")}},x7=function(a){a.Cn&&(a.player.removeEventListener("presentingplayerstatechange",a.Cn),a.Cn=null)},kLa=function(a,b,c){a.Mc=c;
a.player.V("presentingplayerstatechange",new g.iJ(c,b))},lLa=function(a,b,c){var d=!1;
1===b?d=!a.Kr:2===b&&(d=!a.pu);d&&g.kJ(c,8)&&(a.player.pauseVideo(),x7(a))},y7=function(a,b){if(b.key!==a.Xk.key)if(b.key===a.ai.key)i7();
else{if(a.Xo&&!a.pu&&b!==a.ai&&"cast-selector-receiver"!==b.key&&g.uG(a.player.T()))mLa(a);else{var c;(c=!g.T(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.P("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.P("SESSION_INDEX")&&!g.P("LOGGED_IN")))||a.Kr||!a.mp);(c?0:g.uG(a.player.T())||g.yG(a.player.T()))&&nLa(a)}a.Xk=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.T(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.Na(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ia,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=tIa(c))&&(d.locationInfo=c);c=d}$6("Connecting to: "+g.Dj(b));"cast-selector-receiver"==b.key?(b7(c||null),c=c||null,
v6()?s6().setLaunchParams(c):q6("setLaunchParams called before ready.")):!c&&l7()&&Z6()==b.key?B4("yt-remote-connection-change",!0):(i7(),b7(c||null),c=Y6().Kg(),(c=J4(c,b.key))&&j7(c,1))}},nLa=function(a){a.player.Xa().Lb()?a.player.pauseVideo():(a.Cn=function(b){lLa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Cn));
a.mp&&a.mp.Dc();f7()||(n7=!0)},mLa=function(a){a.player.Xa().Lb()?a.player.pauseVideo():(a.Cn=function(b){lLa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Cn));
a.Xo&&a.Xo.Dc();f7()||(n7=!0)},iJa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},j5={"'":"\\'"},oLa={},CIa={YR:"atp",n1:"ska",j0:"que",zZ:"mus",m1:"sus",QV:"dsp",B0:"seq",dZ:"mic",QU:"dpa"},P4,L4="",WIa=RIa("loadCastFramework")||RIa("loadCastApplicationFramework"),YIa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(U4,g.E);g.k=U4.prototype;g.k.mg=function(a){this.B=arguments;this.i=!1;this.gb?this.u=g.Sa()+this.Hf:this.gb=g.Gm(this.C,this.Hf)};
g.k.stop=function(){this.gb&&(g.A.clearTimeout(this.gb),this.gb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.I.apply(null,this.B)))};
g.k.da=function(){this.stop();U4.Ed.da.call(this)};
g.k.LJ=function(){this.u?(this.gb=g.Gm(this.C,this.u-g.Sa()),this.u=null):(this.gb=null,this.l?this.i=!0:(this.i=!1,this.I.apply(null,this.B)))};g.u(V4,g.E);g.k=V4.prototype;g.k.mg=function(a){this.u=arguments;this.gb||this.l?this.i=!0:W4(this)};
g.k.stop=function(){this.gb&&(g.A.clearTimeout(this.gb),this.gb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.gb||(this.i=!1,W4(this))};
g.k.da=function(){g.E.prototype.da.call(this);this.stop()};Y4.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
Y4.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var $4=new g.Wl;g.u($Ia,g.Cl);b5.prototype.i=null;b5.prototype.getOptions=function(){var a;(a=this.i)||(a={},bJa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var z7;g.Ta(aJa,b5);z7=new aJa;g.k=c5.prototype;g.k.jm=null;g.k.vi=!1;g.k.Jp=null;g.k.MA=null;g.k.pp=null;g.k.Dp=null;g.k.Rk=null;g.k.Ql=null;g.k.Dn=null;g.k.Be=null;g.k.Es=0;g.k.zi=null;g.k.Ev=null;g.k.Lk=null;g.k.Zp=-1;g.k.MG=!0;g.k.Mm=!1;g.k.xw=0;g.k.Ru=null;var gJa={},f5={};g.k=c5.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.aQ=function(a){a=a.target;var b=this.Ru;b&&3==o5(a)?b.mg():this.IH(a)};
g.k.IH=function(a){try{if(a==this.Be)a:{var b=o5(this.Be),c=this.Be.I,d=this.Be.getStatus();if(g.Be&&!g.de(10)||g.De&&!g.be("420+")){if(4>b)break a}else if(3>b||3==b&&!g.pg&&!q5(this.Be))break a;this.Mm||4!=b||7==c||(8==c||0>=d?this.i.di(3):this.i.di(2));k5(this);var e=this.Be.getStatus();this.Zp=e;var f=q5(this.Be);(this.vi=200==e)?(4==b&&h5(this),this.I?(hJa(this,b,f),g.pg&&this.vi&&3==b&&(this.B.ya(this.u,"tick",this.TP),this.u.start())):g5(this,f),this.vi&&!this.Mm&&(4==b?this.i.Us(this):(this.vi=
!1,e5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Lk=3,a5(13)):(this.Lk=0,a5(14)),h5(this),i5(this))}}catch(h){this.Be&&q5(this.Be)}finally{}};
g.k.TP=function(){var a=o5(this.Be),b=q5(this.Be);this.Es<b.length&&(k5(this),hJa(this,a,b),this.vi&&4!=a&&e5(this))};
g.k.vP=function(a){Z4((0,g.B)(this.uP,this,a),0)};
g.k.uP=function(a){this.Mm||(k5(this),g5(this,a),e5(this))};
g.k.YF=function(a){Z4((0,g.B)(this.tP,this,a),0)};
g.k.tP=function(a){this.Mm||(h5(this),this.vi=a,this.i.Us(this),this.i.di(4))};
g.k.cancel=function(){this.Mm=!0;h5(this)};
g.k.DP=function(){this.Jp=null;var a=Date.now();0<=a-this.MA?(2!=this.Dp&&this.i.di(3),h5(this),this.Lk=2,a5(18),i5(this)):kJa(this,this.MA-a)};
g.k.getLastError=function(){return this.Lk};g.Ta(m5,g.Wl);var rJa=/^https?$/i,pLa=["POST","PUT"];g.k=m5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.W+"; newUri="+a);b=b?b.toUpperCase():"GET";this.W=a;this.u="";this.I=0;this.za=b;this.ga=!1;this.B=!0;this.i=this.ea?cJa(this.ea):cJa(z7);this.ca=this.ea?this.ea.getOptions():z7.getOptions();this.i.onreadystatechange=(0,g.B)(this.MF,this);try{A4(p5(this,"Opening Xhr")),this.la=!0,this.i.open(b,String(a),!0),this.la=!1}catch(f){A4(p5(this,"Error opening Xhr: "+f.message));qJa(this,f);return}a=
c||"";var e=this.headers.clone();d&&yIa(d,function(f,h){e.set(h,f)});
d=g.cb(e.nh(),oJa);c=g.A.FormData&&a instanceof g.A.FormData;!g.fb(pLa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Ca&&(this.i.responseType=this.Ca);"withCredentials"in this.i&&this.i.withCredentials!==this.ia&&(this.i.withCredentials=this.ia);try{tJa(this),0<this.J&&(this.Y=nJa(this.i),A4(p5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.B)(this.KB,this)):this.X=g.Gm(this.KB,this.J,this)),A4(p5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){A4(p5(this,"Send error: "+f.message)),qJa(this,f)}};
g.k.KB=function(){"undefined"!=typeof g.D_&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.I=8,p5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(p5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),n5(this))};
g.k.da=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),n5(this,!0));m5.Ed.da.call(this)};
g.k.MF=function(){this.na()||(this.la||this.L||this.C?sJa(this):this.CO())};
g.k.CO=function(){sJa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==o5(this)};
g.k.getStatus=function(){try{return 2<o5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=uJa.prototype;g.k.yw=null;g.k.zg=null;g.k.Su=!1;g.k.YG=null;g.k.zt=null;g.k.Ry=null;g.k.zw=null;g.k.Ma=null;g.k.Lj=-1;g.k.aq=null;g.k.kq=null;g.k.connect=function(a){this.zw=a;a=r5(this.i,null,this.zw);a5(3);this.YG=Date.now();var b=this.i.J;null!=b?(this.aq=b[0],(this.kq=b[1])?(this.Ma=1,vJa(this)):(this.Ma=2,t5(this))):(y4(a,"MODE","init"),this.zg=new c5(this,void 0,void 0,void 0),this.zg.jm=this.yw,d5(this.zg,a,!1,null,!0),this.Ma=0)};
g.k.CK=function(a){if(a)this.Ma=2,t5(this);else{a5(4);var b=this.i;b.Gi=b.Vk.Lj;A5(b,9)}a&&this.di(2)};
g.k.Ax=function(a){return this.i.Ax(a)};
g.k.abort=function(){this.zg&&(this.zg.cancel(),this.zg=null);this.Lj=-1};
g.k.LB=function(){return!1};
g.k.PF=function(a,b){this.Lj=a.Zp;if(0==this.Ma)if(b){try{var c=this.l.parse(b)}catch(d){c=this.i;c.Gi=this.Lj;A5(c,2);return}this.aq=c[0];this.kq=c[1]}else c=this.i,c.Gi=this.Lj,A5(c,2);else if(2==this.Ma)if(this.Su)a5(7),this.Ry=Date.now();else if("11111"==b){if(a5(6),this.Su=!0,this.zt=Date.now(),c=this.zt-this.YG,!g.Be||g.de(10)||500>c)this.Lj=200,this.zg.cancel(),a5(12),s5(this.i,this,!0)}else a5(8),this.zt=this.Ry=Date.now(),this.Su=!1};
g.k.Us=function(){this.Lj=this.zg.Zp;if(this.zg.vi)0==this.Ma?this.kq?(this.Ma=1,vJa(this)):(this.Ma=2,t5(this)):2==this.Ma&&((!g.Be||g.de(10)?!this.Su:200>this.Ry-this.zt)?(a5(11),s5(this.i,this,!1)):(a5(12),s5(this.i,this,!0)));else{0==this.Ma?a5(9):2==this.Ma&&a5(10);var a=this.i;this.zg.getLastError();a.Gi=this.Lj;A5(a,2)}};
g.k.Zr=function(){return this.i.Zr()};
g.k.isActive=function(){return this.i.isActive()};
g.k.di=function(a){this.i.di(a)};g.k=u5.prototype;g.k.Fi=null;g.k.Eq=null;g.k.ng=null;g.k.Wd=null;g.k.Aw=null;g.k.At=null;g.k.zC=null;g.k.Vs=null;g.k.yr=0;g.k.uM=0;g.k.zf=null;g.k.il=null;g.k.Pj=null;g.k.Um=null;g.k.Vk=null;g.k.Cv=null;g.k.So=-1;g.k.zE=-1;g.k.Gi=-1;g.k.zo=0;g.k.ho=0;g.k.Nm=8;g.Ta(xJa,g.Cl);g.Ta(yJa,g.Cl);g.k=u5.prototype;g.k.connect=function(a,b,c,d,e){a5(0);this.Aw=b;this.Eq=c||{};d&&void 0!==e&&(this.Eq.OSID=d,this.Eq.OAID=e);this.C?(Z4((0,g.B)(this.SC,this,a),100),CJa(this)):this.SC(a)};
g.k.SC=function(a){this.Vk=new uJa(this);this.Vk.yw=this.Fi;this.Vk.l=this.B;this.Vk.connect(a)};
g.k.LB=function(){return 0==this.Ma};
g.k.getState=function(){return this.Ma};
g.k.WF=function(a){this.il=null;GJa(this,a)};
g.k.VF=function(){this.Pj=null;this.Wd=new c5(this,this.l,"rpc",this.I);this.Wd.jm=this.Fi;this.Wd.xw=0;var a=this.zC.clone();w4(a,"RID","rpc");w4(a,"SID",this.l);w4(a,"CI",this.Cv?"0":"1");w4(a,"AID",this.So);v5(this,a);if(!g.Be||g.de(10))w4(a,"TYPE","xmlhttp"),d5(this.Wd,a,!0,this.Vs,!1);else{w4(a,"TYPE","html");var b=this.Wd,c=!!this.Vs;b.Dp=3;b.Rk=x4(a.clone());jJa(b,c)}};
g.k.PF=function(a,b){if(0!=this.Ma&&(this.Wd==a||this.ng==a))if(this.Gi=a.Zp,this.ng==a&&3==this.Ma)if(7<this.Nm){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Pj){if(this.Wd)if(this.Wd.pp+3E3<this.ng.pp)x5(this),this.Wd.cancel(),this.Wd=null;else break a;z5(this);a5(19)}}else this.zE=c[1],0<this.zE-this.So&&37500>c[2]&&this.Cv&&0==this.ho&&!this.Um&&(this.Um=Z4((0,g.B)(this.YM,this),6E3));else A5(this,11)}else b!=oLa.EU.i&&A5(this,11);else if(this.Wd==
a&&x5(this),!g.rc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.So=e[0];e=e[1];2==this.Ma?"c"==e[0]?(this.l=e[1],this.Vs=e[2],e=e[3],null!=e?this.Nm=e:this.Nm=6,this.Ma=3,this.zf&&this.zf.OC(),this.zC=r5(this,this.Zr()?this.Vs:null,this.Aw),HJa(this)):"stop"==e[0]&&A5(this,7):3==this.Ma&&("stop"==e[0]?A5(this,7):"noop"!=e[0]&&this.zf&&this.zf.NC(e),this.ho=0)}}};
g.k.YM=function(){null!=this.Um&&(this.Um=null,this.Wd.cancel(),this.Wd=null,z5(this),a5(20))};
g.k.Us=function(a){if(this.Wd==a){x5(this);this.Wd=null;var b=2}else if(this.ng==a)this.ng=null,b=1;else return;this.Gi=a.Zp;if(0!=this.Ma)if(a.vi)1==b?(b=$4,b.dispatchEvent(new xJa(b,a.Dn?a.Dn.length:0,Date.now()-a.pp,this.zo)),w5(this),this.u.length=0):HJa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Gi)){if(d=1==b)this.ng||this.il||1==this.Ma||2<=this.zo?d=!1:(this.il=Z4((0,g.B)(this.WF,this,a),IJa(this,this.zo)),this.zo++,d=!0);d=!(d||2==b&&z5(this))}if(d)switch(c){case 1:A5(this,
5);break;case 4:A5(this,10);break;case 3:A5(this,6);break;case 7:A5(this,12);break;default:A5(this,2)}}};
g.k.WK=function(a){if(!g.fb(arguments,this.Ma))throw Error("Unexpected channel state: "+this.Ma);};
g.k.IQ=function(a){a?a5(2):(a5(1),JJa(this,8))};
g.k.Ax=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new m5;a.ia=!1;return a};
g.k.isActive=function(){return!!this.zf&&this.zf.isActive(this)};
g.k.di=function(a){var b=$4;b.dispatchEvent(new yJa(b,a))};
g.k.Zr=function(){return!(!g.Be||g.de(10))};
g.k=KJa.prototype;g.k.OC=function(){};
g.k.NC=function(){};
g.k.MC=function(){};
g.k.jx=function(){};
g.k.wD=function(){return{}};
g.k.isActive=function(){return!0};g.k=LJa.prototype;g.k.isEmpty=function(){return g.gb(this.i)&&g.gb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.fb(this.i,a)||g.fb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.PCa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.l,a)};
g.k.qg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Ta(B5,g.E);g.k=B5.prototype;g.k.nP=function(){this.Hf=Math.min(3E5,2*this.Hf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Hf+15E3*Math.random();g.en(this.i,a);this.l=g.Sa()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Hf=5E3};g.Ta(C5,KJa);g.k=C5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Nf=function(a){return this.u.Nf(a)};
g.k.V=function(a,b){return this.u.V.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.Ei(this.u),OJa(this),g.Ei(this.l),this.l=null,this.Y=function(){return""})};
g.k.na=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.W="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ca+"/test";b=this.ca+"/bind";var d=new u5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ea),e=this.i;e&&(e.zf=null);d.zf=this;this.i=d;D5(this);if(this.i){d=g.P("ID_TOKEN");var f=this.i.Fi||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Fi=f}e?(3!=e.getState()&&0==EJa(e)||e.getState(),this.i.connect(a,b,this.I,e.l,e.So)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Yb(c,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(c):E5(this)&&(D5(this),DJa(this.i,c))};
g.k.OC=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)DJa(this.i,a[b])}this.V("handlerOpened")};
g.k.MC=function(a){var b=2==a&&401==this.i.Gi;4==a||b||this.l.start();this.V("handlerError",a,b)};
g.k.jx=function(a){if(!this.l.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.wD=function(){var a={v:2};this.W&&(a.gsessionid=this.W);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Yb(a,this.C);return a};
g.k.NC=function(a){"S"==a[0]?this.W=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),BJa(this.i)):this.V("handlerMessage",new MJa(a[0],a[1]))};
g.k.bv=function(a){(this.I.loungeIdToken=a)||this.l.stop();if(this.ia&&this.i){var b=this.i.Fi||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Fi=b}};
g.k.kQ=function(){this.l.isActive();0==EJa(this.i)&&this.connect(this.C,this.B)};F5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
F5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
F5.prototype.C=function(a){a(Error("request timed out"))};var VJa=Date.now(),I5=null,L5=Array(50),K5=-1,M5=!1;g.Ta(N5,g.R);N5.prototype.Kg=function(){return this.screens};
N5.prototype.contains=function(a){return!!I4(this.screens,a)};
N5.prototype.get=function(a){return a?J4(this.screens,a):null};
N5.prototype.info=function(a){J5(this.I,a)};g.u(O5,g.R);g.k=O5.prototype;g.k.start=function(){!this.i&&isNaN(this.gb)&&this.gG()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.gb)||(g.wo(this.gb),this.gb=NaN)};
g.k.da=function(){this.stop();g.R.prototype.da.call(this)};
g.k.gG=function(){this.gb=NaN;this.i=g.Tp(G5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.B)(this.NJ,this),onError:(0,g.B)(this.MJ,this),onTimeout:(0,g.B)(this.OJ,this)})};
g.k.NJ=function(a,b){this.i=null;var c=b.screen||{};c.dialId=this.B;c.name=this.I;var d=-1;this.C&&c.shortLivedLoungeToken&&c.shortLivedLoungeToken.value&&c.shortLivedLoungeToken.refreshIntervalMs&&(c.screenIdType="shortLived",c.loungeToken=c.shortLivedLoungeToken.value,d=c.shortLivedLoungeToken.refreshIntervalMs);this.V("pairingComplete",new D4(c),d)};
g.k.MJ=function(a){this.i=null;a.status&&404==a.status?this.l>=qLa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=qLa[this.l],this.gb=g.uo((0,g.B)(this.gG,this),a),this.l++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.OJ=function(){this.i=null;this.V("pairingFailed",Error("Server not responding"))};
var qLa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(Q5,N5);g.k=Q5.prototype;g.k.start=function(){P5(this)&&this.V("screenChange");!g.Hu("yt-remote-lounge-token-expiration")&&ZJa(this);g.wo(this.i);this.i=g.uo((0,g.B)(this.start,this),1E4)};
g.k.add=function(a,b){P5(this);WJa(this,a);R5(this,!1);this.V("screenChange");b(a);a.token||ZJa(this)};
g.k.remove=function(a,b){var c=P5(this);YJa(this,a)&&(R5(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.Av=function(a,b,c,d){var e=P5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,R5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.da=function(){g.wo(this.i);Q5.Ed.da.call(this)};
g.k.xL=function(a){P5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}R5(this,!b);b&&J5(this.I,"Missed "+b+" lounge tokens.")};
g.k.wL=function(a){J5(this.I,"Requesting lounge tokens failed: "+a)};g.u(T5,g.R);g.k=T5.prototype;g.k.start=function(){var a=parseInt(g.Hu("yt-remote-fast-check-period")||"0",10);(this.B=g.Sa()-144E5<a?0:a)?W5(this):(this.B=g.Sa()+3E5,g.Gu("yt-remote-fast-check-period",this.B),this.Mz())};
g.k.isEmpty=function(){return g.Pb(this.i)};
g.k.update=function(){S5("Updating availability on schedule.");var a=this.I(),b=g.Db(this.i,function(c,d){return c&&!!J4(a,d)},this);
V5(this,b)};
g.k.da=function(){g.wo(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.R.prototype.da.call(this)};
g.k.Mz=function(){g.wo(this.u);this.u=NaN;this.l&&this.l.abort();var a=aKa(this);if(z4(a)){var b=G5(this.C,"/pairing/get_screen_availability");this.l=H5(this.C,b,{lounge_token:g.Kb(a).join(",")},(0,g.B)(this.WO,this,a),(0,g.B)(this.VO,this))}else V5(this,{}),W5(this)};
g.k.WO=function(a,b){this.l=null;var c=g.Kb(aKa(this));if(g.yb(c,g.Kb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;V5(this,d);W5(this)}else this.Gd("Changing Screen set during request."),this.Mz()};
g.k.VO=function(a){this.Gd("Screen availability failed: "+a);this.l=null;W5(this)};
g.k.Gd=function(a){J5("OnlineScreenService",a)};g.Ta(X5,N5);g.k=X5.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.V("screenChange"),this.i.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Av=function(a,b,c,d){this.l.contains(a)?this.l.Av(a,b,c,d):(a="Updating name of unknown screen: "+a.name,J5(this.I,a),d(Error(a)))};
g.k.Kg=function(a){return a?this.screens:g.nb(this.screens,g.Ne(this.u,function(b){return!this.contains(b)},this))};
g.k.MB=function(){return g.Ne(this.Kg(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.NB=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new O5(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.Ei(l);e(Y5(h,m),n)});
l.subscribe("pairingFailed",function(m){g.Ei(l);f(m)});
l.start();return(0,g.B)(l.stop,l)};
g.k.PJ=function(a,b,c,d){g.Tp(G5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(e,f){var h=new D4(f.screen||{});if(!h.name||eKa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);eKa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(Y5(this,h))},this),
onError:(0,g.B)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.k.da=function(){g.Ei(this.l);g.Ei(this.i);X5.Ed.da.call(this)};
g.k.DL=function(){gKa(this);this.V("screenChange");this.i.update()};
X5.prototype.dispose=X5.prototype.dispose;g.Ta($5,g.R);g.k=$5.prototype;g.k.getScreen=function(){return this.B};
g.k.ag=function(a){this.na()||(a&&b6(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.k.info=function(a){J5(this.ia,a)};
g.k.OB=function(){return null};
g.k.Xz=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){b6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.da=function(){this.Xz("");$5.Ed.da.call(this)};g.u(c6,$5);g.k=c6.prototype;g.k.Wz=function(a){if(this.l){if(this.l==a)return;b6(this,"Overriding cast session with new session object");pKa(this);this.ca=!1;this.W="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea);lKa(this,"getMdxSessionStatus")};
g.k.To=function(a){this.info("launchWithParams no-op for Cast: "+g.Dj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.B)(function(){this.ag()},this),(0,g.B)(function(){this.ag(Error("Failed to stop receiver app."))},this)):this.ag(Error("Stopping cast device without session."))};
g.k.Xz=function(){};
g.k.da=function(){this.info("disposeInternal");pKa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ea));this.l=null;$5.prototype.da.call(this)};
g.k.HP=function(a,b){if(!this.na())if(b){var c=X4(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Dj(c));switch(d){case "mdxSessionStatus":jKa(this,c);break;case "loungeToken":mKa(this,c);break;default:b6(this,"Unknown youtube message: "+d)}}else b6(this,"Unable to parse message.")}else b6(this,"No data in message.")};
g.k.ND=function(a,b,c,d){g.wo(this.L);this.L=0;dKa(this.u,this.i.label,a,this.i.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(b6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.uo((0,g.B)(this.ND,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.OB=function(){return this.l};
g.k.QJ=function(a){this.na()||a||(b6(this,"Cast session died."),this.ag())};g.u(f6,$5);g.k=f6.prototype;g.k.Wz=function(a){this.l=a;this.l.addUpdateListener(this.ga)};
g.k.To=function(a){this.la=a;this.X()};
g.k.stop=function(){wKa(this);this.l?this.l.stop((0,g.B)(this.ag,this,null),(0,g.B)(this.ag,this,"Failed to stop DIAL device.")):this.ag()};
g.k.da=function(){wKa(this);this.l&&this.l.removeUpdateListener(this.ga);this.l=null;$5.prototype.da.call(this)};
g.k.RJ=function(a){this.na()||a||(b6(this,"DIAL session died."),this.C(),this.C=g.Ia,this.ag())};g.u(j6,$5);j6.prototype.stop=function(){this.ag()};
j6.prototype.Wz=function(){};
j6.prototype.To=function(){g.wo(this.l);this.l=NaN;var a=J4(this.u.Kg(),this.i.label);a?a6(this,a):this.ag(Error("No such screen"))};
j6.prototype.da=function(){g.wo(this.l);this.l=NaN;$5.prototype.da.call(this)};g.u(k6,g.R);g.k=k6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.W||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.B)(this.GO,this);c=new chrome.cast.ApiConfig(c,(0,g.B)(this.RF,this),f,d,e);c.customDialLaunchCallback=(0,g.B)(this.tN,this);chrome.cast.initialize(c,(0,g.B)(function(){this.na()||
(chrome.cast.addReceiverActionListener(this.I),SJa(),this.l.subscribe("onlineScreenChange",(0,g.B)(this.PB,this)),this.u=yKa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.B)(function(h){this.Gd("Failed to set initial custom receivers: "+g.Dj(h))},this)),this.V("yt-remote-cast2-availability-change",m6(this)),b(!0))},this),(0,g.B)(function(h){this.Gd("Failed to initialize API: "+g.Dj(h));
b(!1)},this))};
g.k.rQ=function(a,b){l6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)l6("Unsetting old screen status: "+this.i.i.friendlyName),n6(this,null)}if(a&&b){if(!this.i){c=J4(this.l.Kg(),a);if(!c){l6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){l6("setConnectedScreenStatus: Screen with id type to be short lived.");return}var d=xKa(this,c);d||(l6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(d),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.B)(function(e){this.Gd("Failed to set initial custom receivers: "+g.Dj(e))},this)));
l6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);n6(this,new j6(this.l,d),!0)}this.i.Xz(b)}else l6("setConnectedScreenStatus: no screen.")};
g.k.sQ=function(a){this.na()?this.Gd("Setting connection data on disposed cast v2"):this.i?this.i.To(a):this.Gd("Setting connection data without a session")};
g.k.TJ=function(){this.na()?this.Gd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),n6(this,null)):l6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.B)(this.RF,this),(0,g.B)(this.ZO,this))};
g.k.da=function(){this.l.unsubscribe("onlineScreenChange",(0,g.B)(this.PB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.I);var a=PJa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Ei(this.i);g.R.prototype.da.call(this)};
g.k.Gd=function(a){J5("Controller",a)};
g.k.TF=function(a,b){this.i==a&&(b||n6(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.DO=function(a,b){if(!this.na())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),l6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)l6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{l6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.V("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:n6(this,
new j6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:n6(this,new f6(this.l,a,this.C,this.B));break;case chrome.cast.ReceiverType.CAST:n6(this,new c6(this.l,a,this.B));break;default:this.Gd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Gd("Stopping receiver w/o session: "+a.friendlyName)}else this.Gd("onReceiverAction_ called without receiver.")};
g.k.tN=function(a){if(this.na())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Gd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return l6("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);n6(this,new f6(this.l,b,this.C,this.B))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,g6(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=tKa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.ro(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=uKa(b,c)):a=uKa(b,c)):a=i6(b);return a};
g.k.RF=function(a){if(!this.na()){l6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)l6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),n6(this,new c6(this.l,b,this.B),!0);else{this.Gd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=J4(this.l.Kg(),c.label);d&&E4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(l6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ei(this.i),this.i=new c6(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.B)(this.TF,this,this.i)),this.i.To(null));this.i.Wz(a)}}};
g.k.SJ=function(){return this.i?this.i.OB():null};
g.k.ZO=function(a){this.na()||(this.Gd("Failed to estabilish a session: "+g.Dj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&n6(this,null))};
g.k.GO=function(a){l6("Receiver availability updated: "+a);if(!this.na()){var b=m6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;m6(this)!=b&&this.V("yt-remote-cast2-availability-change",m6(this))}};
g.k.PB=function(){this.na()||(this.u=yKa(this),l6("Updating custom receivers: "+g.Dj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.B)(function(){this.Gd("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",m6(this)))};
k6.prototype.setLaunchParams=k6.prototype.sQ;k6.prototype.setConnectedScreenStatus=k6.prototype.rQ;k6.prototype.stopSession=k6.prototype.TJ;k6.prototype.getCastSession=k6.prototype.SJ;k6.prototype.requestSession=k6.prototype.requestSession;k6.prototype.init=k6.prototype.init;k6.prototype.dispose=k6.prototype.dispose;var t6=[];g.k=y6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";z6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.i=a.trackData,this.Xi=a.hasPrevious,this.hasNext=a.hasNext,this.L=a.playerTime,this.J=a.playerTimeAt,this.C=a.seekableStart,this.l=a.seekableEnd,this.I=a.duration,this.W=a.loadedTime,this.B=a.liveIngestionTime,this.u=!isNaN(this.B))};
g.k.Lb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.u?this.I+A6(this):this.I};
g.k.clone=function(){return new y6(E6(this))};g.u(G6,g.R);g.k=G6.prototype;g.k.getState=function(){return this.Ma};
g.k.play=function(){I6(this)?(this.i?this.i.play(null,g.Ia,N6(this,"play")):M6(this,"play"),L6(this,1,C6(H6(this))),this.V("remotePlayerChange")):J6(this,this.play)};
g.k.pause=function(){I6(this)?(this.i?this.i.pause(null,g.Ia,N6(this,"pause")):M6(this,"pause"),L6(this,2,C6(H6(this))),this.V("remotePlayerChange")):J6(this,this.pause)};
g.k.seekTo=function(a){if(I6(this)){if(this.i){var b=H6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Lb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,N6(this,"seekTo",{newTime:a}))}else M6(this,"seekTo",{newTime:a});L6(this,3,a);this.V("remotePlayerChange")}else J6(this,g.Qa(this.seekTo,a))};
g.k.stop=function(){if(I6(this)){this.i?this.i.stop(null,g.Ia,N6(this,"stopVideo")):M6(this,"stopVideo");var a=H6(this);a.index=-1;a.videoId="";z6(a);K6(this,a);this.V("remotePlayerChange")}else J6(this,this.stop)};
g.k.setVolume=function(a,b){if(I6(this)){var c=H6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.B)(function(){J5("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.Gd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.B)(function(){J5("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.Gd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);M6(this,"setVolume",e)}c.muted=b;c.volume=a;K6(this,c)}else J6(this,g.Qa(this.setVolume,a,b))};
g.k.QB=function(a,b){if(I6(this)){var c=H6(this),d={videoId:a};b&&(c.i={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Dj(b.style),g.Yb(d,c.i));M6(this,"setSubtitlesTrack",d);K6(this,c)}else J6(this,g.Qa(this.QB,a,b))};
g.k.setAudioTrack=function(a,b){if(I6(this)){var c=b.getLanguageInfo().getId();M6(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=H6(this);d.audioTrackId=c;K6(this,d)}else J6(this,g.Qa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=H6(this);c=c||0;var m={videoId:a,currentIndex:c};D6(l,a,c);void 0!==b&&(B6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Dj(h));M6(this,"setPlaylist",m);d||K6(this,l)};
g.k.Nu=function(a,b){if(I6(this)){if(a&&b){var c=H6(this);D6(c,a,b);K6(this,c)}M6(this,"previous")}else J6(this,g.Qa(this.Nu,a,b))};
g.k.nextVideo=function(a,b){if(I6(this)){if(a&&b){var c=H6(this);D6(c,a,b);K6(this,c)}M6(this,"next")}else J6(this,g.Qa(this.nextVideo,a,b))};
g.k.gD=function(){I6(this)?M6(this,"dismissAutoplay"):J6(this,this.gD)};
g.k.dispose=function(){if(3!=this.Ma){var a=this.Ma;this.Ma=3;this.V("proxyStateChange",a,this.Ma)}g.R.prototype.dispose.call(this)};
g.k.da=function(){KKa(this);this.u=null;this.B.clear();F6(this,null);g.R.prototype.da.call(this)};
g.k.aA=function(a){if((a!=this.Ma||2==a)&&3!=this.Ma&&0!=a){var b=this.Ma;this.Ma=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.gb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.AO=function(a,b){this.V(a,b)};
g.k.fN=function(a){if(!a)this.Br(null),F6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=H6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)J5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,K6(this,b)}};
g.k.Br=function(a){J5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),LKa(this),this.V("remotePlayerChange")};
g.k.eN=function(a){a?(LKa(this),this.V("remotePlayerChange")):this.Br(null)};
g.k.rA=function(){M6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.mN=function(){var a=HKa();a&&F6(this,a)};
g.k.Gd=function(a){J5("CP",a)};g.u(O6,g.R);g.k=O6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Fb.listId=c);this.Fb.videoId=d;this.Fb.index=h||0;this.Fb.state=3;B6(this.Fb,m);this.B="UNSUPPORTED";P6("Connecting with setPlaylist and params: "+g.Dj(l));this.i.connect({method:"setPlaylist",
params:g.Dj(l)},a,KIa())}else P6("Connecting without params"),this.i.connect({},a,KIa());NKa(this)};
g.k.bv=function(a){this.i.bv(a)};
g.k.dispose=function(){this.na()||(this.V("beforeDispose"),Q6(this,3));g.R.prototype.dispose.call(this)};
g.k.da=function(){R6(this);T6(this);S6(this);g.wo(this.J);this.J=NaN;g.wo(this.L);this.L=NaN;this.u=null;g.Xo(this.W);this.W.length=0;this.i.dispose();g.R.prototype.da.call(this);this.B=this.I=this.l=this.Fb=this.i=null};
g.k.rL=function(){this.vo(2)};
g.k.jN=function(){P6("Channel opened");this.ca&&(this.ca=!1,S6(this),this.Y=g.uo((0,g.B)(function(){P6("Timing out waiting for a screen.");this.vo(1)},this),15E3));
OIa(NJa(this.i),this.ga)};
g.k.gN=function(){P6("Channel closed");isNaN(this.C)?O4(!0):O4();this.dispose()};
g.k.hN=function(a,b){O4();isNaN(this.Vq())?(b&&"shortLived"==this.ea&&this.V("browserChannelAuthError",a),P6("Channel error: "+a+" without reconnection"),this.dispose()):(this.ca=!0,P6("Channel error: "+a+" with reconnection in "+this.Vq()+" ms"),Q6(this,2))};
g.k.iN=function(a){a.params?P6("Received: action="+a.action+", params="+g.Dj(a.params)):P6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=X4(a.params.devices);this.l=g.Qc(a,function(c){return new C4(c)});
a=!!g.cb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
QKa(this,a);break;case "loungeScreenDisconnected":g.lb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
QKa(this,!1);break;case "remoteConnected":var b=new C4(X4(a.params.device));g.cb(this.l,function(c){return b?c.id==b.id:!1})||uIa(this.l,b);
break;case "remoteDisconnected":b=new C4(X4(a.params.device));g.lb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":SKa(this,a);break;case "nowPlaying":UKa(this,a);break;case "onStateChange":TKa(this,a);break;case "onAdStateChange":VKa(this,a);break;case "onVolumeChanged":WKa(this,a);break;case "onSubtitlesTrackChanged":RKa(this,a);break;case "nowAutoplaying":XKa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.V("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.V("autoplayModeChange",this.B);"DISABLED"==this.B&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":YKa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:P6("Unrecognized action: "+a.action)}};
g.k.gQ=function(){if(this.u){var a=this.u;this.u=null;this.Fb.videoId!=a&&U6(this,"getNowPlaying")}};
g.k.nL=function(){var a=3;this.na()||(a=0,isNaN(this.Vq())?E5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.vo=function(a){P6("Disconnecting with "+a);R6(this);this.V("beforeDisconnect",a);1==a&&O4();OJa(this.i,a);this.dispose()};
g.k.lL=function(){var a=this.Fb;this.u&&(a=this.Fb.clone(),D6(a,this.u,a.index));return E6(a)};
g.k.tQ=function(a){var b=new y6(a);b.videoId&&b.videoId!=this.Fb.videoId&&(this.u=b.videoId,g.wo(this.J),this.J=g.uo((0,g.B)(this.gQ,this),5E3));var c=[];this.Fb.listId==b.listId&&this.Fb.videoId==b.videoId&&this.Fb.index==b.index||c.push("remoteQueueChange");this.Fb.playerState==b.playerState&&this.Fb.volume==b.volume&&this.Fb.muted==b.muted&&C6(this.Fb)==C6(b)&&g.Dj(this.Fb.i)==g.Dj(b.i)||c.push("remotePlayerChange");this.Fb.reset(a);g.Ab(c,function(d){this.V(d)},this)};
g.k.MD=function(){var a=this.i.I.id,b=g.cb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Vq=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Sa():NaN};
g.k.hL=function(){return this.B||"UNSUPPORTED"};
g.k.iL=function(){return this.I||""};
g.k.UJ=function(){if(!isNaN(this.Vq())){var a=this.i.l;a.i.mg();a.start()}};
g.k.pQ=function(a,b){U6(this,a,b);PKa(this)};
g.k.RB=function(){var a=g.Pq("SID","")||"",b=g.Pq("SAPISID","")||"",c=g.Pq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.sf(g.Xe(a),2);b=g.sf(g.Xe(b),2);c=g.sf(g.Xe(c),2);return g.sf(g.Xe(a+","+b+","+c),2)};
O6.prototype.subscribe=O6.prototype.subscribe;O6.prototype.unsubscribeByKey=O6.prototype.Nf;O6.prototype.getProxyState=O6.prototype.nL;O6.prototype.disconnect=O6.prototype.vo;O6.prototype.getPlayerContextData=O6.prototype.lL;O6.prototype.setPlayerContextData=O6.prototype.tQ;O6.prototype.getOtherConnectedRemoteId=O6.prototype.MD;O6.prototype.getReconnectTimeout=O6.prototype.Vq;O6.prototype.getAutoplayMode=O6.prototype.hL;O6.prototype.getAutoplayVideoId=O6.prototype.iL;O6.prototype.reconnect=O6.prototype.UJ;
O6.prototype.sendMessage=O6.prototype.pQ;O6.prototype.getXsrfToken=O6.prototype.RB;g.u(V6,N5);g.k=V6.prototype;g.k.Kg=function(a){return this.Gf.$_gs(a)};
g.k.contains=function(a){return!!this.Gf.$_c(a)};
g.k.get=function(a){return this.Gf.$_g(a)};
g.k.start=function(){this.Gf.$_st()};
g.k.add=function(a,b,c){this.Gf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Gf.$_r(a,b,c)};
g.k.Av=function(a,b,c,d){this.Gf.$_un(a,b,c,d)};
g.k.da=function(){for(var a=0,b=this.i.length;a<b;++a)this.Gf.$_ubk(this.i[a]);this.i.length=0;this.Gf=null;N5.prototype.da.call(this)};
g.k.VJ=function(){this.V("screenChange")};
g.k.hO=function(){this.V("onlineScreenChange")};
X5.prototype.$_st=X5.prototype.start;X5.prototype.$_gspc=X5.prototype.PJ;X5.prototype.$_gsppc=X5.prototype.NB;X5.prototype.$_c=X5.prototype.contains;X5.prototype.$_g=X5.prototype.get;X5.prototype.$_a=X5.prototype.add;X5.prototype.$_un=X5.prototype.Av;X5.prototype.$_r=X5.prototype.remove;X5.prototype.$_gs=X5.prototype.Kg;X5.prototype.$_gos=X5.prototype.MB;X5.prototype.$_s=X5.prototype.subscribe;X5.prototype.$_ubk=X5.prototype.Nf;var h7=null,n7=!1,W6=null,X6=null,m7=null,a7=[];g.u(o7,g.E);g.k=o7.prototype;g.k.da=function(){g.E.prototype.da.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.wb;a.unsubscribe("proxyStateChange",this.OF,this);a.unsubscribe("remotePlayerChange",this.Hr,this);a.unsubscribe("remoteQueueChange",this.Lu,this);a.unsubscribe("previousNextChange",this.LF,this);a.unsubscribe("nowAutoplaying",this.GF,this);a.unsubscribe("autoplayDismissed",this.gF,this);this.wb=this.l=null};
g.k.SB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.wb.Ma)if(p7(this)){if(!H6(this.wb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":H6(this.wb).Lb()?this.wb.pause():this.wb.play();break;case "control_play":this.wb.play();break;case "control_pause":this.wb.pause();break;case "control_seek":this.J.mg(c[0],c[1]);break;case "control_subtitles_set_track":q7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.G.getCurrentTime();r7(this,0===c?void 0:c);break;case "control_seek":r7(this,c[0]);break;case "control_subtitles_set_track":q7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.cN=function(a){this.L.mg(a)};
g.k.ZQ=function(a){this.SB("control_subtitles_set_track",g.Pb(a)?null:a)};
g.k.cH=function(){var a=this.G.getOption("captions","track");g.Pb(a)||q7(this,a)};
g.k.Ab=function(a){this.l.Ab(a,this.G.getVideoData().lengthSeconds)};
g.k.QN=function(){g.Pb(this.B)||iLa(this,this.B);this.C=!1};
g.k.OF=function(a,b){this.u.stop();2===b&&this.XG()};
g.k.Hr=function(){if(p7(this)){this.i.stop();var a=H6(this.wb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Me=1;break;case 1082:case 1083:this.l.Me=0;break;default:this.l.Me=-1}switch(a.playerState){case 1081:case 1:this.tb(new g.dK(8));this.WG();break;case 1085:case 3:this.tb(new g.dK(9));break;case 1083:case 0:this.tb(new g.dK(2));this.J.stop();this.Ab(this.G.getVideoData().lengthSeconds);break;case 1084:this.tb(new g.dK(4));break;case 2:this.tb(new g.dK(4));this.Ab(C6(a));
break;case -1:this.tb(new g.dK(64));break;case -1E3:this.tb(new g.dK(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=H6(this.wb).i;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,iLa(this,a));a=H6(this.wb);-1===a.volume||Math.round(this.G.getVolume())===a.volume&&this.G.isMuted()===a.muted||this.W.isActive()||this.yH()}else hLa(this)};
g.k.LF=function(){this.G.V("mdxpreviousnextchange")};
g.k.Lu=function(){p7(this)||hLa(this)};
g.k.GF=function(a){isNaN(a)||this.G.V("mdxnowautoplaying",a)};
g.k.gF=function(){this.G.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){p7(this)&&this.wb.setAudioTrack(this.G.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===H6(this.wb).playerState?r7(this,a):b&&this.wb.seekTo(a)};
g.k.yH=function(){var a=this;if(p7(this)){var b=H6(this.wb);this.events.Gb(this.X);b.muted?this.G.mute():this.G.unMute();this.G.setVolume(b.volume);this.X=this.events.N(this.G,"onVolumeChange",function(c){gLa(a,c)})}};
g.k.WG=function(){this.i.stop();if(!this.wb.na()){var a=H6(this.wb);a.Lb()&&this.tb(new g.dK(8));this.Ab(C6(a));this.i.start()}};
g.k.XG=function(){this.u.stop();this.i.stop();var a=this.wb.u.getReconnectTimeout();2==this.wb.Ma&&!isNaN(a)&&this.u.start()};
g.k.tb=function(a){this.u.stop();var b=this.I;if(!g.iK(b,a)){var c=g.V(a,2);c!==g.V(this.I,2)&&this.G.Fn(c);this.I=a;kLa(this.l,b,a)}};g.u(s7,g.W);s7.prototype.Dc=function(){this.i.show()};
s7.prototype.kb=function(){this.i.hide()};
s7.prototype.l=function(){g.KJ("https://support.google.com/youtube/answer/7640706")};
s7.prototype.u=function(){B4("mdx-manual-pairing-popup-ok");this.kb()};g.u(t7,g.W);t7.prototype.Dc=function(){this.i.show()};
t7.prototype.kb=function(){this.i.hide()};
t7.prototype.l=function(){B4("mdx-privacy-popup-cancel");this.kb()};
t7.prototype.u=function(){B4("mdx-privacy-popup-confirm");this.kb()};g.u(u7,g.W);u7.prototype.l=function(a){jLa(this,a.state)};g.u(v7,g.RP);v7.prototype.C=function(){var a=this.G.getOption("remote","receivers");a&&1<a.length&&!this.G.getOption("remote","quickCast")?(this.Nl=g.Bb(a,this.i,this),g.SP(this,g.Qc(a,this.i)),a=this.G.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.bh(a),this.enable(!0)):this.enable(!1)};
v7.prototype.i=function(a){return a.key};
v7.prototype.Ih=function(a){return"cast-selector-receiver"===a?"Cast...":this.Nl[a].name};
v7.prototype.Ue=function(a){g.RP.prototype.Ue.call(this,a);this.G.setOption("remote","currentReceiver",this.Nl[a]);this.bb.kb()};g.u(w7,g.gN);g.k=w7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.ZF(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.T(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.T(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.T(a.experiments,"enable_cast_short_lived_lounge_token")};bLa(b,a);this.subscriptions.push(g.Bo("yt-remote-before-disconnect",this.aN,this));this.subscriptions.push(g.Bo("yt-remote-connection-change",this.HO,this));this.subscriptions.push(g.Bo("yt-remote-receiver-availability-change",
this.NF,this));this.subscriptions.push(g.Bo("yt-remote-auto-connect",this.FO,this));this.subscriptions.push(g.Bo("yt-remote-receiver-resumed",this.EO,this));this.subscriptions.push(g.Bo("mdx-privacy-popup-confirm",this.WP,this));this.subscriptions.push(g.Bo("mdx-privacy-popup-cancel",this.VP,this));this.subscriptions.push(g.Bo("mdx-manual-pairing-popup-ok",this.jM,this));this.NF()};
g.k.load=function(){this.player.cancelPlayback();g.gN.prototype.load.call(this);this.hh=new o7(this,this.player,this.wb);var a=(a=fLa())?a.currentTime:0;var b=l7()?new G6(f7(),void 0):null;0==a&&b&&(a=C6(H6(b)));0!==a&&this.Ab(a);kLa(this,this.Mc,this.Mc);this.player.yj(6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.Xk=this.ai;g.Fi(this.hh,this.wb);this.wb=this.hh=null;g.gN.prototype.unload.call(this);this.player.yj(5);x7(this)};
g.k.da=function(){g.Co(this.subscriptions);g.gN.prototype.da.call(this)};
g.k.oj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.hh.SB.apply(this.hh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Me};
g.k.oL=function(){return this.loaded?this.hh.suggestion:null};
g.k.Xi=function(){return this.wb?H6(this.wb).Xi:!1};
g.k.hasNext=function(){return this.wb?H6(this.wb).hasNext:!1};
g.k.Ab=function(a,b){this.AE=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.AE};
g.k.getProgressState=function(){var a=H6(this.wb),b=this.player.getVideoData();return{allowSeeking:g.T(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Ke():!a.isAdPlaying()&&this.player.Ke(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+A6(a):a.B,isAtLiveHead:1>=(a.u?a.l+A6(a):a.l)-this.getCurrentTime(),loaded:a.W,seekableEnd:a.u?a.l+A6(a):a.l,seekableStart:0<a.C?a.C+
A6(a):a.C}};
g.k.nextVideo=function(){this.wb&&this.wb.nextVideo()};
g.k.Nu=function(){this.wb&&this.wb.Nu()};
g.k.aN=function(a){1===a&&(this.Bz=this.wb?H6(this.wb):null)};
g.k.HO=function(){var a=l7()?new G6(f7(),void 0):null;if(a){var b=this.Xk;this.loaded&&this.unload();this.wb=a;this.Bz=null;b.key!==this.ai.key&&(this.Xk=b,this.load())}else g.Ei(this.wb),this.wb=null,this.loaded&&(this.unload(),(a=this.Bz)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,C6(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.NF=function(){var a=[this.ai],b=a.concat,c=cLa();u6()&&g.Hu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Nl=b.call(a,c);a=g7()||this.ai;y7(this,a);this.player.xa("onMdxReceiversChange")};
g.k.FO=function(){var a=g7();y7(this,a)};
g.k.EO=function(){this.Xk=g7()};
g.k.WP=function(){this.Kr=!0;x7(this);n7=!1;h7&&j7(h7,1);h7=null};
g.k.VP=function(){this.Kr=!1;x7(this);y7(this,this.ai);this.Xk=this.ai;n7=!1;h7=null;this.player.playVideo()};
g.k.jM=function(){this.pu=!0;x7(this);g.Gu("yt-remote-manual-pairing-warning-shown",!0,2592E3);n7=!1;h7&&j7(h7,1);h7=null};
g.k.Fe=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Nl;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?w6():y7(this,b)),this.loaded?this.Xk:this.ai;case "quickCast":return 2===this.Nl.length&&"cast-selector-receiver"===this.Nl[1].key?(b&&w6(),!0):!1}};
g.k.rA=function(){this.wb.rA()};
g.k.si=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.mN.remote=w7;})(_yt_player);
